[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" } 